from . import ums_mixin
from . import ums_institution
from . import ums_college
from . import ums_department
from . import ums_program
from . import ums_course
from . import ums_course_prerequisite
from . import ums_study_plan
from . import ums_learning_outcome
from . import ums_grade_scheme
